### ISSUE TITLE
Don't show password in plain text on activation

### ISSUE THREAD

**Issue by brashrebel** [brashrebel/wordcrash-functionality#2]
When a user activates their account, they go to a page that just shows their password in plain text. That ain't cool.

**Comment by dcbaldwin1** [comment]
Definitely not cool. Is this what is happening on the newest version (single install)? It's been a while, I can't remember if this is default WordPress functionality. Is it?

**Comment by brashrebel** [comment]
I think this is resolved. We migrated the site yesterday to a single install instead of on a multisite and it is running the latest version of WP which I'm not sure the last install was.
