### ISSUE TITLE
Account Activation

### ISSUE THREAD

**Issue by joelworsham** [brashrebel/wordcrash-functionality#4]
_From @dcbaldwin1 on September 9, 2015 0:30_

The first activation email states 'After you activate, you will receive _another email_ with your login.'

I never received another email with my login.

_Copied from original issue: brashrebel/wordcrash-theme#10_

**Comment by joelworsham** [comment]
_From @brashrebel on September 9, 2015 0:32_

Good point! I know that text can be filtered so we should add a function in the functionality plugin we're using. @dcbaldwin1 do you know how to and have the time to do it?

**Comment by joelworsham** [comment]
_From @dcbaldwin1 on September 9, 2015 1:19_

A wp-content/plugins plugin? Yeah I think I could help but not for a week or so - I'm catching from knee surgery.

**Comment by joelworsham** [comment]
_From @brashrebel on September 9, 2015 19:8_

If you have time to get to it, here's the repo where we'd like to add such a function:

https://github.com/brashrebel/wordcrash-functionality

**Comment by joelworsham** [comment]
_From @dcbaldwin1 on September 9, 2015 21:21_

I should be able to look in the next week.

**Comment by joelworsham** [comment]
_From @dcbaldwin1 on September 12, 2015 21:50_

I have a local install of WordPress multisite and a couple sites are set up (one being wordcrash) and running smoothly, except for emails. I'm using MAMP. I can't get any emails to send at all. I don't have MAMP Pro either, which I may end up having to get. I've tried WP SMTP Mail and some other MAMP (free) work arounds to no avail.

Have you ever gotten emails working locally with multisite?

**Comment by joelworsham** [comment]
_From @brashrebel on September 14, 2015 18:26_

@dcbaldwin1 yes, as I've had intermittent problems to. Though they all went away as soon as I started using wpMandrill. Network activate that and setup a free account with Mandrill and you'll be all set.

**Comment by joelworsham** [comment]
_From @dcbaldwin1 on September 15, 2015 0:10_

Favorited wpMandrill. Thanks for the pointer.

**Comment by brashrebel** [comment]
This should be fixed now that we're on a single install.
